# Generated by Django 4.1.5 on 2023-05-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_university_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default='Stranger', max_length=100),
        ),
    ]
