# Generated by Django 4.1.5 on 2023-06-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_email_alter_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='origin',
            field=models.BooleanField(default=True),
        ),
    ]
