# Generated by Django 4.1.5 on 2023-06-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_account_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='origin',
            field=models.BooleanField(default=False),
        ),
    ]
