# Generated by Django 4.1.5 on 2023-10-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_account_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='universityName',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
