# Generated by Django 4.1.5 on 2023-10-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='terms',
            field=models.BooleanField(default=False),
        ),
    ]
