# Generated by Django 4.1.5 on 2023-10-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_account_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='terms',
            field=models.BooleanField(default=True),
        ),
    ]
