# Generated by Django 4.1.5 on 2023-10-22 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_account_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='flags',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
