# Generated by Django 4.1.5 on 2023-11-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_accounttoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountToken',
        ),
    ]
