# Generated by Django 4.1.5 on 2023-11-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_account_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('uni_name', models.CharField(max_length=100)),
                ('uni_address', models.CharField(max_length=400)),
                ('issue_faced', models.CharField(max_length=10000)),
            ],
        ),
    ]
