# Generated by Django 4.1.5 on 2023-11-12 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_registrationerror'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='universityName',
        ),
    ]
