# Generated by Django 4.1.5 on 2023-11-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_account_universityname'),
    ]

    operations = [
        migrations.CreateModel(
            name='deleted_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=10000)),
            ],
        ),
    ]
