# Generated by Django 4.1.5 on 2023-11-28 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='question',
            field=models.CharField(default='question', max_length=2005),
            preserve_default=False,
        ),
    ]
