# Generated by Django 4.1.5 on 2023-11-28 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_publicchatroom_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicroomchatmessage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='publicroomchatmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='PublicChatRoom',
        ),
        migrations.DeleteModel(
            name='PublicRoomChatMessage',
        ),
    ]
