# Generated by Django 4.1.5 on 2023-11-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_activeusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveUsers',
        ),
    ]
