# Generated by Django 4.1.5 on 2023-11-12 22:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0004_activeusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveVideoUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(blank=True, related_name='video_users', to=settings.AUTH_USER_MODEL, verbose_name='video_users')),
            ],
        ),
    ]
