# Generated by Django 4.1.5 on 2023-11-15 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0005_activevideousers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeusers',
            name='count',
        ),
        migrations.AddField(
            model_name='activeusers',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='all_active_users', to=settings.AUTH_USER_MODEL, verbose_name='all_active_users'),
        ),
    ]
