# Generated by Django 4.1.5 on 2023-09-19 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomchatmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
