# Generated by Django 4.1.5 on 2023-05-17 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystranger_app', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupconnect',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to='mystranger_app.profile', verbose_name='User_1'),
        ),
        migrations.AlterField(
            model_name='groupconnect',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_2', to='mystranger_app.profile', verbose_name='User_2'),
        ),
        migrations.AlterField(
            model_name='waitingarea',
            name='users',
            field=models.ManyToManyField(blank=True, to='mystranger_app.profile', verbose_name='waiting-users'),
        ),
    ]
