# Generated by Django 4.1.5 on 2023-05-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystranger_app', '0004_alter_groupconnect_user1_alter_groupconnect_user2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='lat',
            field=models.FloatField(default=23.4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='lon',
            field=models.FloatField(default=25.4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='universityAddress',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='university',
            name='universityName',
            field=models.CharField(default='Galgotia', max_length=150),
            preserve_default=False,
        ),
    ]
