# Generated by Django 4.1.5 on 2023-06-23 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mystranger_app', '0005_university_lat_university_lon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('universityName', models.CharField(max_length=150)),
                ('universityAddress', models.CharField(blank=True, max_length=1000)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
        ),
    ]
