# Generated by Django 4.1.5 on 2023-06-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystranger_app', '0007_alter_universityprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='nearbyList',
            field=models.ManyToManyField(blank=True, to='mystranger_app.university', verbose_name='nearby_universities'),
        ),
    ]
