# Generated by Django 4.1.5 on 2023-06-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystranger_app', '0008_university_nearbylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityprofile',
            name='nearbyList',
            field=models.ManyToManyField(blank=True, to='mystranger_app.universityprofile', verbose_name='nearby_universities'),
        ),
    ]
