# Generated by Django 4.1.5 on 2023-06-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystranger_app', '0009_universityprofile_nearbylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprofile',
            name='nearbyList',
            field=models.ManyToManyField(blank=True, to='mystranger_app.university', verbose_name='nearby_universities'),
        ),
    ]
