# Generated by Django 4.1.5 on 2023-07-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystranger_app', '0010_alter_universityprofile_nearbylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
