# Generated by Django 4.1.5 on 2023-10-22 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mystranger_app', '0012_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='flags',
            name='Flagger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Flagged_by', to=settings.AUTH_USER_MODEL, verbose_name='Flagged_by'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flags',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Flags', to=settings.AUTH_USER_MODEL, verbose_name='Flagged'),
        ),
    ]
