# Generated by Django 4.1.5 on 2023-10-25 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mystranger_app', '0013_flags_flagger_alter_flags_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=9000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Feedback', to=settings.AUTH_USER_MODEL, verbose_name='Feedback')),
            ],
        ),
    ]
