# Generated by Django 4.1.5 on 2023-11-11 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mystranger_app', '0016_universityprofile_allnearbyusers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='allNearbyUsers',
            field=models.ManyToManyField(blank=True, related_name='all_nearby_users', to=settings.AUTH_USER_MODEL, verbose_name='nearby_uni_users'),
        ),
        migrations.AlterField(
            model_name='university',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.AlterField(
            model_name='universityprofile',
            name='allNearbyUsers',
            field=models.ManyToManyField(blank=True, related_name='all_nearby_users_profile', to=settings.AUTH_USER_MODEL, verbose_name='nearby_uni_users'),
        ),
        migrations.AlterField(
            model_name='universityprofile',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='profile_users', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
    ]
